# Generated by Django 4.2.11 on 2024-06-18 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studcourseregapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptitle', models.CharField(max_length=30)),
                ('planguage', models.CharField(max_length=30)),
                ('pduration', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studcourseregapp.student')),
            ],
        ),
    ]
